### ISSUE TITLE
Serious memory leak

### ISSUE THREAD

**Issue by wgliang** [mibk/dupl#16]
There are two places have serious memory leak：

- 1.https://github.com/mibk/dupl/blob/master/suffixtree/dupl.go#L34
- 2.https://github.com/mibk/dupl/blob/master/main.go#L166

**Comment by shurcooL** [comment]
_(Unrelated to the issue, but related to your comment, see [this note](https://news.ycombinator.com/item?id=14809172) about pasting links to code.)_

**Comment by mibk** [comment]
@wgliang Can you, please, provide more information? What makes you think that? Thank you.

**Comment by wgliang** [comment]
![86aa074a-a65d-4696-b088-102a74069293_lx](https://user-images.githubusercontent.com/8739301/28760257-1ce6314e-75d8-11e7-917d-7450452cee4d.png)

**Comment by mibk** [comment]
I'm sorry but the picture haven't said much to me. Can you give me the steps to reproduce the problem? I don't even know what tool you used for making the report in the picture (was it goreporter?).

By just looking at the code, I can't see any problem there. I would like to fix this though.
