### ISSUE TITLE
Output in a format more easily digested by editors

### ISSUE THREAD

**Issue by alecthomas** [mibk/dupl#2]
Hello,

Interesting tool. Would it be possible to have an alternate output format that is more easily integrated with editors/IDEs?

Instead of:

```
found 3 clones:
  loc 1: main.go, line 139-139,
  loc 2: main.go, line 140-140,
  loc 3: main.go, line 150-150,
```

Something like:

```
main.go:139-139: duplicate of main.go:140-140, main.go:150-150
main.go:140-140: duplicate of main.go:139-139, main.go:150-150
main.go:150-150: duplicate of main.go:139-139, main.go:140-140
```

**Comment by shurcooL** [comment]
Instead of outputting results as text, then parsing them again, what about making it a library with a small command-line wrapper around it.

Similar to how there's go/format the library, and gofmt the binary.

**Comment by mibk** [comment]
I agree with @shurcooL. We could refactor `main.go` to make it only a default implementation with some reasonable outputs. I think both outputs (text and html) should be improved, but adding outputs for specific use cases is out of the scope.

1. We could arrange the format of the default text output. Any suggestions?
2. I would like to refactor the packages for the output to be more usable, so it would be easy to implement specific outputs.

**Comment by alecthomas** [comment]
As I mentioned, this is primarily for editor integration so a package wouldn't in itself be useful. JSON is also not the best for this as most editors have some builtin facility for parsing simple compiler-like output.

**Comment by mibk** [comment]
By making it a package it would be trivial for anyone to make a tiny frontend app to print the output in a desired format. But should there be implemented another output format just for convenience? If the format would by parsable by a reasonable number of editors then I think it could be added.

**Comment by mibk** [comment]
Just found that Acme supports locations as:
```
found 3 clones:
  loc 1: main.go:140,145
  loc 2: main.go:150,155
  loc 3: main.go:167,172
```
(*But Acme is not like the other editors.*)
By clicking at the filename it opens that file and selects the specified range. I could easily rewrite the current text output to the one mentioned above as I think it is both better and readable. The following format is probably even better:
```
found 3 clones:
  main.go:140,145
  main.go:150,155
  main.go:167,172
```

For the other editors, is it necessary to mention **n** locations of a clone group **n^2** times?

**Comment by alecthomas** [comment]
I'm not 100% sure, but they're typically in the form `<file>:<line>: <message>`. For example, [VIM](http://vim.wikia.com/wiki/Errorformat_and_makeprg) uses `set errorformat=%f:%l:%m`.

**Comment by mibk** [comment]
If the clone group would concise of a large number of locations, the output would be IMHO too messy. What about `<file>:<line>: clone group <id>` like:

```
main.go:140: clone group 1
main.go:150: clone group 1
main.go:167: clone group 1
main.go:20: clone group 2
main.go 25: clone group 2
...
```

**Comment by alecthomas** [comment]
I agree that large groups would be unwieldy. The problem with that format is that, in an editor, you often only see one message at a time. So all you'd see is eg. `main.go:140: clone group 1`. This doesn't give enough context.

But upon consideration, I think all you need is a circular reference to the *next* member of the group. eg.

```
main.go:140-145: duplicate of main.go:150-155
main.go:150-155: duplicate of main.go:167-152
main.go:167-152: duplicate of main.go:140-145
```

When viewing each individual line, you'd have enough information to find the next duplicate.

**Comment by mibk** [comment]
Yes, a circular representation is much better. I can do a prototype. What about the name of the corresponding flag? `-ide`, as the purpose is meant for IDEs?

**Comment by alecthomas** [comment]
Sounds good!

**Comment by shurcooL** [comment]
> What about the name of the corresponding flag? -ide, as the purpose is meant for IDEs?

A flag name suggestion, if you wish. Git commands fall into categories of ["plumbing" and "porcelain"](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain). So you could have an optional `--plumbing` bool flag that is false by default, and setting it to true enables "plumbing" output (easy to parse, to be consumed by scripts, IDEs, etc.)

https://github.com/shurcooL/gostatus/blob/3e4092d49bb356fb4d202860addbc64b6091a02e/main.go#L22

**Comment by mibk** [comment]
@shurcooL Thank you. It sounds good.

**Comment by mibk** [comment]
Have you noticed the pull request?

**Comment by shurcooL** [comment]
Yep, I've reviewed it just now. I think you should ask @alecthomas for feedback.

**Comment by alecthomas** [comment]
The output is perfect, thanks!

**Comment by alecthomas** [comment]
I've [added support](https://github.com/alecthomas/gometalinter/commit/9d392c3a98b68dbfd444f0dc74c6a9157d97647e) for dupl to gometalinter. Thanks for the change!

**Comment by mibk** [comment]
Thanks for the addition :-)
