### ISSUE TITLE
Add flag to ignore certain directories (e.g. generated code)

### ISSUE THREAD

**Issue by tamird** [mibk/dupl#6]
Not currently possible short of enumerating all non-ignored directories.

**Comment by mibk** [comment]
What about:

```bash
find . -name "*.go" -not -path "./excluded_dir/*" | dupl -files
```

I would rather avoid implementing any method for selecting certain files as it is IMHO a very complex problem. I would prefer ortogonality: let other programs do their job for selecting files and let the **dupl** do its job for finding clones.

I understand that it is not as convenient as it could be, but I think the added complexity isn't worth it. It would start by adding a flag for ignoring certain directories and then someone could propose a flag for ignoring `*_test.go` files and so on. Anyway, it would never be as powerful as the **find** command is.

If it would be a frequent task you can add it to a *Makefile* for example...

What do you think about it?

**Comment by shurcooL** [comment]
> I would rather avoid implementing any method for selecting certain files as it is IMHO a very complex problem. I would prefer ortogonality: let other programs do their job for selecting files and let the **dupl** do its job for finding clones.

I highly agree.

**Comment by tamird** [comment]
Agreed. Thanks!
