### ISSUE TITLE
dupl not the same as dupl *.go

### ISSUE THREAD

**Issue by cep21** [mibk/dupl#7]
Running ```dupl``` will find duplicates across files.  Running ```dupl *.go``` will only find duplicates inside each file.  Given the feedback of https://github.com/mibk/dupl/issues/6 is it possible for multiple files specified on the command line to work the same as dupl on a directory?

**Comment by cep21** [comment]
Specifically, I see

```
< dupl -t 100 *.go

Found total 0 clone groups.
```

and

```
< dupl -t 100 eventlimits.go orglimits.go 

Found total 0 clone groups.
```

But I see
```
< dupl -t 100
found 2 clones:
  eventlimits.go:29,44
  orglimits.go:212,227
```

I believe this is because *.go does not work across files.

**Comment by mibk** [comment]
The way you were using dupl is not the way it worked. It only considered the first argument which had to be a directory. But I've added this feature as it seemed reasonable. You can check it in this pull request #8. If it worked as you would expect I would merge it.

**Comment by alecthomas** [comment]
Thanks!

**Comment by mibk** [comment]
And I thank both of you for the feedback!
